# THESE TEST CASES WHERE GENERATED BY ANTIGRAVITY'S GEMINI 3.1 PRO (HIGH)

import pytest
import polars as pl
import math
from Autonoma.tools.analysis import AnalysisTools

@pytest.fixture
def sample_df():
    """Fixture providing a diverse DataFrame for testing."""
    return pl.DataFrame({
        "id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "age": [25, 30, 35, 40, 25, 30, 100, 25, 30, 35],  # 100 is an outlier
        "name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Heidi", "Ivan", "Judy"],
        "score": [85.5, 90.0, None, 75.5, 88.0, 92.5, 60.0, 85.5, 90.0, 78.0],
        "category": ["A", "B", "A", "C", "A", "B", "C", "A", "B", "A"],
        "constant_col": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "quasi_constant": ["X", "X", "X", "X", "X", "X", "X", "X", "X", "Y"]
    })

@pytest.fixture
def empty_df():
    """Fixture providing an empty DataFrame."""
    return pl.DataFrame({
        "A": pl.Series([], dtype=pl.Int64),
        "B": pl.Series([], dtype=pl.String)
    })

@pytest.fixture
def no_numeric_df():
    """Fixture providing a DataFrame with no numerical columns."""
    return pl.DataFrame({
        "A": ["a", "b", "c"],
        "B": ["x", "y", "z"]
    })

class TestGetDFInfo:
    def test_get_df_info_normal(self, sample_df):
        info = AnalysisTools.get_df_info(sample_df)
        assert info["shape"] == (10, 7)
        assert len(info["columns"]) == 7
        assert info["dtypes"]["id"] == "Int64"
        assert info["dtypes"]["name"] == "String"
        assert info["null_counts"]["score"] == 1
        assert info["null_counts"]["id"] == 0

    def test_get_df_info_empty(self, empty_df):
        info = AnalysisTools.get_df_info(empty_df)
        assert info["shape"] == (0, 2)
        assert info["null_counts"]["A"] == 0

class TestGetNumericalSummary:
    def test_all_numeric(self, sample_df):
        summary = AnalysisTools.get_numerical_summary(sample_df)
        assert "numerical_summary" in summary
        stats = {row["statistic"]: row for row in summary["numerical_summary"]}
        assert "age" in stats["mean"]
        assert "score" in stats["mean"]
        # categorical/string columns should not be here
        assert "name" not in stats["mean"]

    def test_selected_columns(self, sample_df):
        summary = AnalysisTools.get_numerical_summary(sample_df, columns=["age", "score"])
        assert "numerical_summary" in summary
        stats = {row["statistic"]: row for row in summary["numerical_summary"]}
        assert "age" in stats["mean"]
        assert "score" in stats["mean"]
        assert "id" not in stats["mean"]

    def test_no_numeric_found(self, no_numeric_df):
        summary = AnalysisTools.get_numerical_summary(no_numeric_df)
        assert "error" in summary
        assert "No Numerical Columns" in summary["error"]

    def test_empty_df_with_numeric(self):
        empty_numeric = pl.DataFrame({"A": pl.Series([], dtype=pl.Int64)})
        summary = AnalysisTools.get_numerical_summary(empty_numeric)
        # Should return a summary but counts are 0
        assert "numerical_summary" in summary
        stats = {row["statistic"]: row for row in summary["numerical_summary"]}
        assert stats["count"]["A"] == 0.0

class TestGetCategoricalDistribution:
    def test_normal_distribution(self, sample_df):
        dist = AnalysisTools.get_categorical_distribution(sample_df, column="category", top_n=2)
        assert dist["column"] == "category"
        assert len(dist["distribution"]) == 2
        # 'A' is most frequent (5 times)
        assert dist["distribution"][0]["category"] == "A"
        assert dist["distribution"][0]["count"] == 5
        assert dist["distribution"][0]["percentage"] == 0.5

    def test_column_not_found(self, sample_df):
        dist = AnalysisTools.get_categorical_distribution(sample_df, column="non_existent")
        assert "error" in dist
        assert "not found" in dist["error"]

class TestDetectOutliers:
    def test_detect_outliers_normal(self, sample_df):
        # Age 100 should be an outlier with a tight threshold
        result = AnalysisTools.detect_outliers(sample_df, column="age", threshold=2.5)
        assert "error" not in result
        assert result["outlier_count"] == 1
        assert result["column"] == "age"
        assert result["percentage"] == 10.0

    def test_zero_variance(self, sample_df):
        result = AnalysisTools.detect_outliers(sample_df, column="constant_col")
        assert result["outlier_count"] == 0
        assert "Zero Variance" in result["note"]

    def test_column_not_found(self, sample_df):
        result = AnalysisTools.detect_outliers(sample_df, column="non_existent")
        assert "error" in result
        assert "not found" in result["error"]

class TestGetCorrelation:
    def test_normal_correlation(self, sample_df):
        # Drop constant_col to prevent RuntimeWarning for 0 std deviation
        df = sample_df.drop("constant_col")
        result = AnalysisTools.get_correlation(df)
        assert "error" not in result
        assert "matrix" in result
        assert "columns" in result
        assert "id" in result["columns"]
        assert "age" in result["columns"]

    def test_insufficient_numeric(self, no_numeric_df):
        result = AnalysisTools.get_correlation(no_numeric_df)
        assert "error" in result
        assert "Insufficient Numerical Columns" in result["error"]
        
    def test_one_numeric_column(self):
        df = pl.DataFrame({"A": [1, 2, 3], "B": ["a", "b", "c"]})
        result = AnalysisTools.get_correlation(df)
        assert "error" in result
        assert "Insufficient Numerical Columns" in result["error"]

class TestGetSkew:
    def test_normal_skew(self, sample_df):
        result = AnalysisTools.get_skew(sample_df)
        assert "error" not in result
        assert "skews" in result
        assert "columns" in result
        assert "age" in result["columns"]

    def test_no_numeric(self, no_numeric_df):
        result = AnalysisTools.get_skew(no_numeric_df)
        assert "error" in result
        assert "No Numerical Columns" in result["error"]

class TestGetTargetCorrelations:
    def test_normal_target(self, sample_df):
        result = AnalysisTools.get_target_correlations(sample_df, target="age")
        assert "error" not in result
        assert result["target"] == "age"
        assert "id" in result["correlations"]
        assert "score" in result["correlations"]
        assert "age" not in result["correlations"]

    def test_target_not_found(self, sample_df):
        result = AnalysisTools.get_target_correlations(sample_df, target="non_existent")
        assert "error" in result
        assert "not found" in result["error"]

    def test_target_not_numerical(self, sample_df):
        result = AnalysisTools.get_target_correlations(sample_df, target="category")
        assert "error" in result
        assert "must be numerical" in result["error"]

    def test_insufficient_columns(self):
        df = pl.DataFrame({"target": [1, 2, 3], "cat": ["A", "B", "C"]})
        result = AnalysisTools.get_target_correlations(df, target="target")
        assert "error" in result
        assert "Insufficient numerical columns" in result["error"]

class TestGetColumnCardinality:
    def test_normal_cardinality(self, sample_df):
        result = AnalysisTools.get_column_cardinality(sample_df, column="category")
        assert "error" not in result
        assert result["column"] == "category"
        assert result["n_unique"] == 3

    def test_column_not_found(self, sample_df):
        result = AnalysisTools.get_column_cardinality(sample_df, column="non_existent")
        assert "error" in result
        assert "not found" in result["error"]

    def test_not_categorical(self, sample_df):
        result = AnalysisTools.get_column_cardinality(sample_df, column="age")
        assert "error" in result
        assert "numerical/boolean" in result["error"]

class TestCheckLowVariance:
    def test_normal_check(self, sample_df):
        result = AnalysisTools.check_low_variance(sample_df, threshold=0.85)
        assert "error" not in result
        assert "constant_col" in result["quasi_cols"]
        assert "quasi_constant" in result["quasi_cols"]
        # score has no dominant value exceeding 0.85 (max is 85.5 twice => 20%)
        assert "score" not in result["quasi_cols"]
        assert result["threshold"] == 0.85
        
    def test_no_low_variance(self, sample_df):
        result = AnalysisTools.check_low_variance(sample_df, threshold=1.1)
        assert len(result["quasi_cols"]) == 0
