# THESE TEST CASES WHERE GENERATED BY ANTIGRAVITY'S GEMINI 3.1 PRO (HIGH)

import pytest
import os
import joblib
import numpy as np
import polars as pl
from sklearn.linear_model import LogisticRegression, Ridge
from Autonoma.tools.modeling import ModellingTools

@pytest.fixture
def cls_data():
    """Classification dataset (20 samples, 2 features, balanced classes)."""
    # Deterministic data
    X = pl.DataFrame({
        "f1": [0.1, 0.9, 0.2, 0.8] * 5,
        "f2": [0.8, 0.2, 0.7, 0.3] * 5
    })
    y = pl.Series("y", [0, 1, 0, 1] * 5)
    return X, y

@pytest.fixture
def reg_data():
    """Regression dataset (20 samples, 2 features)."""
    X = pl.DataFrame({
        "f1": [1.0, 2.0, 3.0, 4.0] * 5,
        "f2": [2.0, 4.0, 6.0, 8.0] * 5
    })
    y = pl.Series("y", [1.5, 2.5, 3.5, 4.5] * 5)
    return X, y

class TestGetEstimator:
    def test_valid_estimators(self):
        est = ModellingTools.get_estimator('logistic')
        assert isinstance(est, LogisticRegression)
        
        est2 = ModellingTools.get_estimator('ridge')
        assert isinstance(est2, Ridge)

    def test_invalid_estimator(self):
        with pytest.raises(ValueError, match="Invalid model_type"):
            ModellingTools.get_estimator('invalid_model')

class TestGridSearch:
    def test_grid_search_classification(self, cls_data):
        X, y = cls_data
        params = {'C': [0.1, 1.0, 10.0]}
        res = ModellingTools.grid_search('logistic', params, X, y, folds=2)
        assert "params" in res
        assert "C" in res["params"]
        assert "score" in res

    def test_grid_search_regression(self, reg_data):
        X, y = reg_data
        params = {'alpha': [0.1, 1.0]}
        res = ModellingTools.grid_search('ridge', params, X, y, folds=2)
        assert "params" in res
        assert "alpha" in res["params"]
        assert "score" in res

class TestRandomSearch:
    def test_random_search_classification(self, cls_data):
        X, y = cls_data
        params = {'n_estimators': [5, 10, 15], 'max_depth': [2, 3]}
        res = ModellingTools.random_search('forest_c', params, X, y, folds=2, iters=2)
        assert "params" in res
        assert "score" in res

    def test_random_search_invalid_params(self, cls_data):
        X, y = cls_data
        # Missing param for random forest, but will crash sklearn.
        # We just test the integration passes.
        params = {'invalid_param': [1, 2]}
        with pytest.raises(ValueError):
            # Sklearn raises ValueError if parameter is not valid for estimator
            ModellingTools.random_search('forest_c', params, X, y, folds=2, iters=2)

class TestLinearModels:
    def test_fit_linear_model(self, cls_data):
        X, y = cls_data
        params = {'C': 1.0}
        res = ModellingTools.linear_models('logistic', X, y, params, fit=True)
        assert "model_path" in res
        assert os.path.exists(res["model_path"])
        
        # Verify model was fitted by checking if it has coef_ attribute
        model = joblib.load(res["model_path"])
        assert hasattr(model, "coef_")

    def test_unfitted_linear_model(self, reg_data):
        X, y = reg_data
        params = {'alpha': 1.0}
        res = ModellingTools.linear_models('ridge', X, y, params, fit=False)
        assert "model_path" in res
        
        # Verify model is saved but NOT fitted
        model = joblib.load(res["model_path"])
        assert not hasattr(model, "coef_")

class TestTreeModels:
    def test_fit_tree_model(self, cls_data):
        X, y = cls_data
        params = {'max_depth': 2}
        res = ModellingTools.tree_models('decision_c', X, y, None, None, params, fit=True)
        assert "model_path" in res
        model = joblib.load(res["model_path"])
        assert hasattr(model, "tree_") # fitted attribute for decision trees

    def test_xgb_with_eval_set(self, cls_data):
        X, y = cls_data
        params = {'n_estimators': 5, 'max_depth': 2}
        # Use same data for train and val to test integration
        res = ModellingTools.tree_models('xgb_c', X, y, X, y, params, fit=True)
        assert "model_path" in res
        model = joblib.load(res["model_path"])
        # If early stopping rounds was added successfully by the function
        assert "early_stopping_rounds" in params or getattr(model, "early_stopping_rounds", None) == 5

class TestEvaluation:
    @pytest.fixture(autouse=True)
    def setup_models(self, cls_data, reg_data):
        X_c, y_c = cls_data
        X_r, y_r = reg_data
        
        # Train and save classification model
        self.cls_model_path = ModellingTools.linear_models('logistic', X_c, y_c, {}, fit=True)["model_path"]
        
        # Train and save regression model
        self.reg_model_path = ModellingTools.linear_models('ridge', X_r, y_r, {}, fit=True)["model_path"]

    def test_eval_classification(self, cls_data):
        X, y = cls_data
        res = ModellingTools.eval_classification(self.cls_model_path, X, y)
        assert "accuracy" in res
        assert "precision" in res
        assert "recall" in res
        assert "f1" in res
        assert "classification_report" in res
        # roc_auc should be present and valid because LogisticRegression has predict_proba
        assert res["roc_auc"] is not None

    def test_eval_classification_no_proba(self, cls_data):
        X, y = cls_data
        # Train RidgeClassifier (no predict_proba) to test edge case
        model = Ridge().fit(X.to_numpy(), y.to_numpy())
        path = ModellingTools.save_model(model, 'ridge_cls')
        
        # Wait, standard Ridge is for regression. 
        # But we can just use the Regression model to predict float and see it crash, or just mock predict_proba.
        # Actually, let's just train an SVM without probability=True (not exposed in simple modeling.py but we can instantiate it).
        from sklearn.svm import SVC
        svc = SVC(probability=False).fit(X.to_numpy(), y.to_numpy())
        svc_path = ModellingTools.save_model(svc, 'svc')
        
        res = ModellingTools.eval_classification(svc_path, X, y)
        assert "accuracy" in res
        # Without predict_proba, roc_auc should be gracefully handled as None per our Exception block
        assert res.get("roc_auc") is None

    def test_eval_regression(self, reg_data):
        X, y = reg_data
        res = ModellingTools.eval_regression(self.reg_model_path, X, y)
        assert "mse" in res
        assert "rmse" in res
        assert "mae" in res
