# THESE TEST CASES WHERE GENERATED BY ANTIGRAVITY'S GEMINI 3.1 PRO (HIGH)

import pytest
import polars as pl
import numpy as np
import warnings
from datetime import date
from Autonoma.tools.preprocessing import PreprocessingTools

@pytest.fixture
def sample_df():
    """Fixture providing a diverse DataFrame for testing preprocessing."""
    return pl.DataFrame({
        "id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "age": [25, 30, 35, 40, 25, 30, 100, 25, 30, 35],  # 100 is an outlier
        "score": [85.5, 90.0, None, 75.5, 88.0, 92.5, 60.0, 85.5, 90.0, 78.0],
        "category": ["A", "B", "A", "C", "A", "B", "C", "A", "B", "A"],
        "target": [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
        "constant": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "negatives": [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10],
        "dates": [date(2023, 1, 1), date(2023, 2, 2), date(2023, 3, 3), date(2023, 4, 4), date(2023, 5, 5),
                  date(2023, 6, 6), date(2023, 7, 7), date(2023, 8, 8), date(2023, 9, 9), date(2023, 10, 10)]
    })

@pytest.fixture
def numeric_df(sample_df):
    """Fixture providing strictly numerical DataFrame for KNN and scaling."""
    return sample_df.select(["id", "age", "score", "target", "constant", "negatives"])

@pytest.fixture
def train_test_dfs():
    """Fixture providing train and test dataframes for scaling."""
    X_train = pl.DataFrame({
        "id": [1, 2, 3, 4, 5, 6, 7, 8],
        "feat1": [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0],
        "feat2": [1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8]
    })
    X_test = pl.DataFrame({
        "id": [9, 10],
        "feat1": [90.0, 100.0],
        "feat2": [9.9, 10.1]
    })
    return X_train, X_test

class TestDropColumn:
    def test_normal_drop(self, sample_df):
        res, df = PreprocessingTools.drop_column(sample_df, "category")
        assert "success" in res
        assert "category" not in df.columns

    def test_missing_column(self, sample_df):
        res, df = PreprocessingTools.drop_column(sample_df, "non_existent")
        assert "error" in res
        assert "non_existent" in res["error"]
        assert df.shape == sample_df.shape

class TestFillNulls:
    def test_fill_median(self, sample_df):
        res, df = PreprocessingTools.fill_nulls(sample_df, 'median', 'score')
        assert "success" in res
        assert df.get_column("score").null_count() == 0
        
    def test_fill_mode(self, sample_df):
        res, df = PreprocessingTools.fill_nulls(sample_df, 'mode', 'score')
        assert "success" in res
        assert df.get_column("score").null_count() == 0

    def test_fill_below(self, sample_df):
        res, df = PreprocessingTools.fill_nulls(sample_df, 'below', 'score')
        assert "success" in res
        assert df.get_column("score").null_count() == 0

    def test_fill_knn(self, numeric_df):
        res, df = PreprocessingTools.fill_nulls(numeric_df, 'knn', 'score')
        assert "success" in res
        assert df.get_column("score").null_count() == 0

    def test_fill_custom(self, sample_df):
        res, df = PreprocessingTools.fill_nulls(sample_df, 'custom', 'category', custom_val="Missing")
        assert "success" in res

    def test_fill_custom_missing_val(self, sample_df):
        res, df = PreprocessingTools.fill_nulls(sample_df, 'custom', 'score')
        assert "error" in res
        assert "Missing required custom_val" in res["error"]

    def test_invalid_method(self, sample_df):
        res, df = PreprocessingTools.fill_nulls(sample_df, 'invalid_method', 'score')  # type: ignore
        assert "error" in res

class TestDropOutliers:
    def test_normal_drop(self, sample_df):
        res, df = PreprocessingTools.drop_outliers(sample_df, "age", threshold=2.0)
        assert "original_dim" in res
        assert df.height < sample_df.height
        assert 100 not in df.get_column("age").to_list()

    def test_zero_variance(self, sample_df):
        # We suppress numpy warnings here since pandas/polars/numpy might warn about 0 std deviation division
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res, df = PreprocessingTools.drop_outliers(sample_df, "constant", threshold=3.0)
        assert "error" in res
        assert "zero variance" in res["error"].lower()

    def test_missing_column(self, sample_df):
        res, df = PreprocessingTools.drop_outliers(sample_df, "non_existent")
        assert "error" in res

class TestTransformColumn:
    def test_log_transform(self, sample_df):
        res, df = PreprocessingTools.transform_column(sample_df, "age", "log")
        assert "success" in res

    def test_exp_transform(self, sample_df):
        res, df = PreprocessingTools.transform_column(sample_df, "age", "exp")
        assert "success" in res

    def test_box_cox(self, sample_df):
        res, df = PreprocessingTools.transform_column(sample_df, "age", "box-cox")
        assert "success" in res

    def test_yeo_johnson(self, sample_df):
        res, df = PreprocessingTools.transform_column(sample_df, "negatives", "yeo-johnson")
        assert "success" in res

    def test_box_cox_on_negatives_error(self, sample_df):
        # Box-Cox requires strictly positive data. It should catch exception and return error
        res, df = PreprocessingTools.transform_column(sample_df, "negatives", "box-cox")
        assert "error" in res
        assert "failed" in res["error"].lower()

    def test_invalid_method(self, sample_df):
        res, df = PreprocessingTools.transform_column(sample_df, "age", "invalid")  # type: ignore
        assert "error" in res

class TestScaleColumn:
    def test_standard_scaler(self, train_test_dfs):
        X_train, X_test = train_test_dfs
        res, X_train_scaled, X_test_scaled = PreprocessingTools.scale_column(X_train, X_test, ["feat1", "feat2"], "standard")
        assert "success" in res
        assert abs(X_train_scaled.get_column("feat1").mean()) < 1e-6  # mean should be close to 0

    def test_robust_scaler(self, train_test_dfs):
        X_train, X_test = train_test_dfs
        res, _, _ = PreprocessingTools.scale_column(X_train, X_test, ["feat1"], "robust")
        assert "success" in res

    def test_missing_columns(self, train_test_dfs):
        X_train, X_test = train_test_dfs
        res, _, _ = PreprocessingTools.scale_column(X_train, X_test, ["feat1", "non_existent"])
        assert "error" in res

    def test_invalid_method(self, train_test_dfs):
        X_train, X_test = train_test_dfs
        res, _, _ = PreprocessingTools.scale_column(X_train, X_test, ["feat1"], "invalid")  # type: ignore
        assert "error" in res

class TestEncodeCategorical:
    def test_onehot(self, sample_df):
        res, df = PreprocessingTools.encode_categorical(sample_df, "category", "onehot", None, None)
        assert "success" in res
        # Check that onehot encoding actually added new columns
        # Expect category_B or category_C to be present because drop_first=True
        assert "category_B" in df.columns or "category_C" in df.columns

    def test_label(self, sample_df):
        res, df = PreprocessingTools.encode_categorical(sample_df, "category", "label", None, None)
        assert "success" in res
        # Valid physical dtype for categorical label
        assert df.get_column("category").dtype in [
            pl.UInt32, pl.Int32, pl.UInt8, pl.Int8, pl.Int64, pl.UInt64, pl.Categorical
        ]

    def test_ordinal(self, sample_df):
        res, df = PreprocessingTools.encode_categorical(sample_df, "category", "ordinal", None, None)
        assert "success" in res
        assert df.get_column("category").dtype in [pl.Float64, pl.Float32]

    def test_target(self, sample_df):
        res, df = PreprocessingTools.encode_categorical(sample_df, "category", "target", "target", None)
        assert "success" in res

    def test_target_missing_col(self, sample_df):
        res, df = PreprocessingTools.encode_categorical(sample_df, "category", "target", None, None)
        assert "error" in res

    def test_custom(self, sample_df):
        custom_map = {"A": 1, "B": 2, "C": 3}
        res, df = PreprocessingTools.encode_categorical(sample_df, "category", "custom", None, custom_map)
        assert "success" in res
        assert set(str(x) for x in df.get_column("category").to_list()) == {"1", "2", "3"}

    def test_custom_missing_map(self, sample_df):
        res, df = PreprocessingTools.encode_categorical(sample_df, "category", "custom", None, None)
        assert "error" in res

class TestSplitData:
    def test_train_val_split(self, sample_df):
        # We suppress warnings from sklearn converting polars series to arrays
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res, train, val, test = PreprocessingTools.split_data(sample_df, "target", val_size=0.2, test_size=None)
            
        assert "success" in res
        assert test is None
        assert train.height > 0
        assert val.height > 0

    def test_train_val_test_split(self, sample_df):
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res, train, val, test = PreprocessingTools.split_data(sample_df, "target", val_size=0.2, test_size=0.2)
            
        assert "success" in res
        assert train.height > 0
        assert val.height > 0
        assert test is not None and test.height > 0

class TestCreateFeature:
    def test_arithmetic(self, sample_df):
        # According to schema tools_io.py:
        # {"type": "arithmetic", "col1": "age", "col2": "score", "op": "mul", "new_name": "age_score"}
        operations = [{"type": "arithmetic", "col1": "age", "col2": "score", "op": "mul", "new_name": "age_score"}]
        res, df = PreprocessingTools.create_feature(sample_df, operations)
        assert "success" in res
        assert "age_score" in df.columns

    def test_date_extract(self, sample_df):
        # According to schema tools_io.py:
        # {"type": "date_extract", "col": "dates"}
        operations = [{"type": "date_extract", "col": "dates"}]
        res, df = PreprocessingTools.create_feature(sample_df, operations)
        assert "success" in res
        assert "dates_month" in df.columns
